HASS_BASE_URL = "http://localhost:8123"
TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI2ODMwY2U5YTE3ODA0MTlmODEzYjIxNmVhNzVjYjAxZSIsImlhdCI6MTc0Nzk5MjA2NywiZXhwIjoyMDYzMzUyMDY3fQ.27iGnE0hEet_Y3dECfTDWJNApCPmUIdtjvdhnC4Rd84"
MQTT_BROKER = "localhost"
MQTT_PORT = 1883
SENSOR_FILE = "sensors.json"