@startuml RD_Sistem
skinparam class {
  BackgroundColor white
  ArrowColor black
  DefaultTextAlignment center
}
hide circle

' Zaslonske maske

class "ZM-NadzornaPlosca" as ZM_NadzornaPlosca <<boundary>> <<HA>>{
  -okencePrikazDogodkov
  +gumbOdpriDogodek()
}

class "ZM-Dogodek" as ZM_Dogodek <<boundary>> {
  -poljeID
  -poljeVrsta
  -poljeCas
}

class "ZM-DogodekZvok" as ZM_DogodekZvok <<boundary>> {
  +gumbPredvajajZvok()
}

ZM_DogodekZvok --|> ZM_Dogodek

' Kontrolerji

class "K-NadzornaPlosca" as K_NadzornaPlosca <<controller>> <<HA>>{
  -dogodki
  -naloziDogodke()
  +odpriDogodekZM()
}

' Razredi

class "R-BazaPodatkov" as R_BazaPodatkov <<entity>> {
  -podatki
  +vrniDogodke()
}

class "R-Dogodek" as R_Dogodek <<entity>> {
  -id
  -vrsta
  -cas
}

class "R-DogodekZvok" as R_DogodekZvok <<entity>> {
  -id
  -vrsta
  -cas
}

R_DogodekZvok --|> R_Dogodek

' Povezave

' NadzornaPlosca
ZM_NadzornaPlosca <--> K_NadzornaPlosca
K_NadzornaPlosca <--> R_BazaPodatkov
K_NadzornaPlosca --> ZM_Dogodek

' Baza
R_BazaPodatkov --> R_Dogodek

' Boundary classes (GREEN background)
skinparam class {
  BackgroundColor<<boundary>> #D5F5E3
}

' Controller classes (RED background)
skinparam class {
  BackgroundColor<<controller>> #FADBD8
}

skinparam class {
  BorderColor<<HA>> #007ACC
}

legend right
  |= Barva |= Opis |
  | ZELENA | Ozadje razredov tipa boundary (uporabniški vmesnik) |
  | RDEČA | Ozadje razredov tipa controller (logika/krmilniki) |
  | BELA | Ozadje razredov tipa entity (podatkovni modeli) |
  | MODRA | Rob razredov, ki so že implementirani ali delno implementirani v Home Assistant |
endlegend
@enduml